#!/usr/bin/env python3
"""Generate a profilarr tweaks-layer SQL file seeding custom_format_tests from corpus.json.

Only labels that correspond 1:1 to a custom format's full/title-level semantics are
exported (regex-level labels that differ from CF semantics are harness-only).
"""
import json, sys

corpus_path, out_path = sys.argv[1], sys.argv[2]

# corpus label -> custom_formats.name
LABEL_TO_CF = {
    "Dolby Vision": "Dolby Vision",
    "HDR10+": "HDR10+",
    "CF:Dolby Vision (Without Fallback)": "Dolby Vision (Without Fallback)",
    "CF:HDR": "HDR",
    "CF:SDR(title-part)": "SDR",
    "CF:HDR10 (Missing)(title-part)": "HDR10 (Missing)",
    "CF:HDR (Missing)(title-part)": "HDR (Missing)",
    "Remux": "Remux",
    "German DL": "German DL",
    "CF:DUBBED": "DUBBED",
    "CF:Extras": "Extras",
}

def esc(s: str) -> str:
    return s.replace("'", "''")

corpus = json.load(open(corpus_path))
lines = [
    "-- Profilarr tweaks-layer seed: HDR/DV truth corpus as custom_format_tests rows.",
    "-- Generated by harness/gen_cf_tests.py from harness/corpus.json. Local audit",
    "-- artifact - not part of append-only ops history.",
]
n = 0
for case in corpus["cases"]:
    title = case["title"]
    kind = "series" if ".S01" in title or "S01E" in title else "movie"
    note = case.get("note", "HDR/DV audit corpus")
    for label, cf in LABEL_TO_CF.items():
        if label in case["expect"]:
            should = 1 if case["expect"][label] else 0
            lines.append(
                "INSERT OR IGNORE INTO custom_format_tests "
                "(custom_format_name, title, type, should_match, description) VALUES "
                f"('{esc(cf)}', '{esc(title)}', '{kind}', {should}, '{esc(note)}');"
            )
            n += 1
open(out_path, "w").write("\n".join(lines) + "\n")
print(f"wrote {n} test rows to {out_path}")
